#!/usr/bin/env node
//
// Pre-scan auth helper: sign in the scanner user, complete TOTP, and emit a
// ZAP replacer config that injects the resulting AAL2 access token + the
// scanner-guard header on every request ZAP sends.
//
// Driven by env vars (set by the GitHub Actions workflow):
//   SUPABASE_URL              e.g. https://evpmuoxfrnmustokkaqg.supabase.co
//   SUPABASE_ANON_KEY         project anon key (legacy JWT or sb_publishable_*)
//   ZAP_USER_EMAIL            zap-scanner+<env>@spej.ai
//   ZAP_USER_PASSWORD         password for that user
//   ZAP_TOTP_SECRET           base32 TOTP shared secret captured at enrollment
//   SCANNER_TOKEN             matches the SCANNER_TOKEN secret set on the
//                             Edge Function project — short-circuits side
//                             effects in instrumented functions
//
// Writes `${OUT_FILE:-replacer.conf}` in ZAP's replacer XML format. Apply
// to ZAP via `-z "-config replacer.full_list.replacer..."` OR
// `-configFile replacer.conf` (the latter is what zaproxy/action-*-scan
// accepts via `cmd_options`).
//
// Token TTL is ~1h, which is plenty for one scan. Long scans should re-run
// this script at the workflow level if they exceed that.

import { createClient } from "@supabase/supabase-js";
import * as OTPAuth from "otpauth";
import { writeFileSync } from "node:fs";

const REQUIRED = [
  "SUPABASE_URL",
  "SUPABASE_ANON_KEY",
  "ZAP_USER_EMAIL",
  "ZAP_USER_PASSWORD",
  "ZAP_TOTP_SECRET",
  "SCANNER_TOKEN",
];

const missing = REQUIRED.filter((k) => !process.env[k]);
if (missing.length > 0) {
  console.error(`auth-mint: missing required env vars: ${missing.join(", ")}`);
  process.exit(2);
}

const supabase = createClient(
  process.env.SUPABASE_URL,
  process.env.SUPABASE_ANON_KEY,
  { auth: { persistSession: false, autoRefreshToken: false } },
);

async function main() {
  // Step 1: password sign-in (AAL1).
  const { data: signInData, error: signInErr } = await supabase.auth.signInWithPassword({
    email: process.env.ZAP_USER_EMAIL,
    password: process.env.ZAP_USER_PASSWORD,
  });
  if (signInErr) throw new Error(`signInWithPassword failed: ${signInErr.message}`);

  // Step 2: enumerate enrolled TOTP factors.
  const { data: factorsData, error: factorsErr } = await supabase.auth.mfa.listFactors();
  if (factorsErr) throw new Error(`mfa.listFactors failed: ${factorsErr.message}`);
  const totp = factorsData?.totp?.find((f) => f.status === "verified");
  if (!totp) throw new Error("no verified TOTP factor on scanner user — re-enroll");

  // Step 3: generate current OTP from the stored shared secret.
  const totpDriver = new OTPAuth.TOTP({
    issuer: "Nodak",
    label: process.env.ZAP_USER_EMAIL,
    algorithm: "SHA1",
    digits: 6,
    period: 30,
    secret: OTPAuth.Secret.fromBase32(process.env.ZAP_TOTP_SECRET.replace(/\s+/g, "")),
  });
  const code = totpDriver.generate();

  // Step 4: AAL2 escalation.
  const { error: verifyErr } = await supabase.auth.mfa.challengeAndVerify({
    factorId: totp.id,
    code,
  });
  if (verifyErr) throw new Error(`mfa.challengeAndVerify failed: ${verifyErr.message}`);

  // After challengeAndVerify, the session is now AAL2. Re-fetch session.
  const { data: sessData, error: sessErr } = await supabase.auth.getSession();
  if (sessErr || !sessData.session) {
    throw new Error(`getSession after AAL2 failed: ${sessErr?.message ?? "no session"}`);
  }
  const accessToken = sessData.session.access_token;

  // Step 5: emit ZAP replacer config. Format docs:
  //   https://www.zaproxy.org/docs/desktop/addons/replacer/
  const conf = `# Auto-generated by .zap/auth-mint.mjs — do not hand-edit.
# Injects scanner credentials on every request ZAP issues.
replacer.full_list(0).description=ZAP auth bearer
replacer.full_list(0).enabled=true
replacer.full_list(0).matchtype=REQ_HEADER
replacer.full_list(0).matchstr=Authorization
replacer.full_list(0).regex=false
replacer.full_list(0).replacement=Bearer ${accessToken}
replacer.full_list(0).initiators=
replacer.full_list(1).description=Scanner-guard token
replacer.full_list(1).enabled=true
replacer.full_list(1).matchtype=REQ_HEADER
replacer.full_list(1).matchstr=x-scanner-run
replacer.full_list(1).regex=false
replacer.full_list(1).replacement=${process.env.SCANNER_TOKEN}
replacer.full_list(1).initiators=
`;

  const outFile = process.env.OUT_FILE || "replacer.conf";
  writeFileSync(outFile, conf, "utf8");
  console.log(`auth-mint: wrote ${outFile} (AAL2 JWT, ${accessToken.length} chars)`);
}

main().catch((err) => {
  console.error(`auth-mint: ${err.message}`);
  process.exit(1);
});
